---
# Requires the Prometheus Operator CRDs to be installed.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-validate-monitor
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: certificate-validate
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - cert-manager
