---
apiVersion: v1
kind: Namespace
metadata:
  name: certificate-validate
  labels:
    app: certificate-validate

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: certificate-validate
  namespace: certificate-validate
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: certificate-validate-limits
  namespace: certificate-validate
spec:
  limits:
    - default:
        cpu: "32m"
        memory: "32Mi"
      defaultRequest:
        cpu: "32m"
        memory: "32Mi"
      max:
        cpu: "2"
        memory: "2Gi"
      type: Container