---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - 
      name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./requirements.txt
        pip install pylint
    - 
      name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2
    - 
      name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - 
      name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - 
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  build:
    environment: DOCKERHUB
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [lint, analyze]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build
        run: |
          docker build \
          --no-cache \
          --rm \
          -t $GITHUB_REPOSITORY:latest \
          -f ./Dockerfile .
      - 
        name: Push
        run: docker push $GITHUB_REPOSITORY:latest
