---
name: CI

on:
  push:
  pull_request:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env: 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo -e "$DOCKERHUB_USERNAME"
