---
name: CI

on:
  push:
  pull_request:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_RESPOSITORY: "fabianosanflor/certificate"

jobs:  
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

  build:
    needs: login
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build \
          --no-cache \
          --rm \
          -t ${{ env.DOCKERHUB_RESPOSITORY }}:v0.0.$GITHUB_JOB \
          -f ./Dockerfile .
      
      - name: Push
        run: docker push ${{ env.DOCKERHUB_RESPOSITORY }}:v0.0.$GITHUB_JOB