---
name: CI

on:
  push:
  pull_request:
env:
  DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}

jobs:  
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - shell: bash
        run: |
          echo -e "$DOCKERHUB_USERNAME"
