---
name: CI

on:
  push:
  pull_request:

jobs:  
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
