---
name: CI

on:
  push:
  pull_request:

jobs:  
  login:
    name: Login to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: docker/login-action@1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
